Spring:
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8
  resources:
    static-locations: classpath:/static
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/chat_room?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: nie200188888888
    druid:
      filters: stat
      initialSize: 2
      maxActive: 20
      minIdle: 5
      maxWait: 2000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
  redis:
    timeout: 0
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 40
        max-wait: -1
        max-idle: 40
        min-idle: 0
server:
  port: 8000
mybatis:
  mapper-locations: classpath:/mapper/*.xml
fileData:
  staticAccessPath: "/app/resources/**"
  uploadRealPath: "C:\\data\\"
